Listen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from music import views

urlpatterns = [
    path('', views.main_pg, name='main_pg'),
    path('manage/hariom/', admin.site.urls),
    path('music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from . import views

app_name = 'music'


urlpatterns = [
    path('', views.index, name='index'),
    # path('search<str:find_text>/', views.index, name='index'),
    path('<int:pk>/', views.details, name='details'),
    path('<int:pk>/delete-album/', views.AlbumDelete.as_view(), name='album-delete'),
    path('<int:pk>/add-song/', views.add_song, name='add-song'),
    path('<int:pk>/delete-song/<int:song_pk>/', views.song_delete, name='song-delete'),
    path('<int:pk>/album-favorite/', views.album_favorite, name='album_favorite'),
    path('<int:pk>/song-favorite/<int:song_pk>/', views.song_favorite, name='song_favorite'),
    path('songs/', views.songs, name='songs'),
    path('songs/song-favorite/<int:song_pk>', views.song_page_fav, name='song_page_fav'),
    path('songs/song-delete/<int:song_pk>', views.song_page_del, name='song_page_del'),
    path('songs/add-song/', views.song_create, name='song-create'),
    path('add-album/', views.AlbumCreate.as_view(), name='add-album'),
    # path('register/', views.UserFormView.as_view(), name='register'),
]

music/models.py
from django.db import models
from django.urls import reverse


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=1000)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.album_title + ' - ' + self.artist

    def get_absolute_url(self):
        return reverse('music:details', kwargs={'pk': self.pk})


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField()
    file_type = models.CharField(max_length=20, default='mp3')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from .models import Album, Song
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic import View
from django.contrib.auth import authenticate, login
from .form import UserRegister
from django.urls import reverse_lazy
from music.Coding import corona_api


def main_pg(request):
    return redirect('music:index')


def index(request):
    if request.method == 'POST':
        find_text = request.POST['search']
        if find_text:
            album_with_title = Album.objects.filter(album_title__startswith=find_text)
            album_with_artist = Album.objects.filter(artist__startswith=find_text)
            if album_with_title:
                return render(request, 'music/index.html', {'album': album_with_title[0]})
            elif album_with_artist:
                return render(request, 'music/index.html', {'album': album_with_artist[0]})
            else:
                msg1 = f'No results found for "{find_text}"'
                msg2 = 'please check your spelling or try with a different keyword'
                return render(request, 'music/index.html', {'msg1': msg1, 'msg2': msg2})
    all_albums = Album.objects.all()
    return render(request, 'music/Index.html', {
        'albums': all_albums,
        'india_confirmed': corona_api.india_confirmed,
        'india_active': corona_api.india_active,
        'india_deaths': corona_api.india_deaths,
        'india_recover': corona_api.india_recover,
        'maha_recovered': corona_api.maha_recovered,
        'maha_confirmed': corona_api.maha_confirmed,
        'mumbai_confirmed': corona_api.mumbai_confirmed,
        'india_per_active': corona_api.india_per_active,
        'india_per_recover': corona_api.india_per_recover,
        'india_per_deaths': corona_api.india_per_deaths,
        'maha_per_recover': corona_api.maha_per_recover,
        'mum_per_india': corona_api.mum_per_india,
        })


def details(request, pk):
    album = get_object_or_404(Album, pk=pk)
    return render(request, 'music/Details.html', {'album': album})


# def album_search(request):
#     if request.method == 'POST':
#         find_text = request.POST['search']
#         album = Album.objects.filter(album_title__startswith=find_text)
#         if album:
#             return render(request, 'music/index.html', {'album': album})
#         else:
#             album = Album.objects.filter(artist__startswith=find_text)
#             if album:
#                 return render(request, 'music/index.html', {'album': album})
#     error_message = 'album not found'
#     return render(request, 'music/index_search.html', {'error_message': error_message})


def songs(request):
    if request.method == 'POST':
        find_text = request.POST['search']
        if find_text:
            song_with_title = Song.objects.filter(song_title__startswith=find_text)
            if song_with_title:
                return render(request, 'music/Songs.html', {'song': song_with_title[0]})
            else:
                msg1 = f'No results found for "{find_text}"'
                msg2 = 'please check your spelling or try with a different keyword'
                return render(request, 'music/Songs.html', {'msg1': msg1, 'msg2': msg2})
    songs = Song.objects.all()
    template = 'music/Songs.html'
    return render(request, template, {'all_songs': songs})


def song_page_fav(request, song_pk):
    song = get_object_or_404(Song, pk=song_pk)
    if song.is_favorite:
        song.is_favorite = False
    else:
        song.is_favorite = True
    song.save()
    return redirect('music:songs')


def song_page_del(request, song_pk):
    song = get_object_or_404(Song, pk=song_pk)
    song.delete()
    return redirect('music:songs')


def album_favorite(request, pk):
    album = get_object_or_404(Album, pk=pk)
    if album.is_favorite:
        album.is_favorite = False
    else:
        album.is_favorite = True
    album.save()
    return redirect('music:index')


def song_favorite(request, pk, song_pk):
    album = get_object_or_404(Album, pk=pk)
    song = get_object_or_404(Song, pk=song_pk)
    if song.is_favorite:
        song.is_favorite = False
    else:
        song.is_favorite = True
    song.save()
    return redirect('music:details', album.id)


# def add_album(request):
#     if request.method == 'POST':
#         artist = request.POST['artst']
#
#     return render(request, 'music/AddAlbum.html', {})

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


def song_create(request):
    if request.method == 'GET':
        all_albums = Album.objects.all()
        if not all_albums:
            msg1 = f'Cannot add songs without any album'
            msg2 = 'please add at least one album to add any songs to it'
            return render(request, 'music/song_form.html', {'msg1': msg1, 'msg2': msg2})
        return render(request, 'music/song_form.html', {'all_albums': all_albums})
    if request.method == 'POST':
        song = Song()
        song.song_title = request.POST['song_title']
        song.audio_file = request.FILES['audio_file']
        album_id = request.POST['sel']
        album = get_object_or_404(Album, pk=album_id)
        song.album = album
        song.save()
    return redirect('music:songs')


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


def song_delete(request, pk, song_pk):
    album = get_object_or_404(Album, pk=pk)
    song = get_object_or_404(Song, pk=song_pk)
    song.delete()
    return redirect('music:details', album.id)


# class SongCreate(CreateView):
#     model = Song
#
#     def dispatch(self, request, *args, **kwargs):
#         """
#         Overridden so we can make sure the `Ipsum` instance exists
#         before going any further.
#         """
#         self.album = get_object_or_404(Album, pk=kwargs['pk'])
#         return super().dispatch(request, *args, **kwargs)
#
#     def form_valid(self, form):
#         form.instance.album = self.album
#         return super().form_valid(form)

class UserFormView(View):
    form_class = UserRegister
    template_name = 'music/register_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})


def add_song(request, pk):
    album = get_object_or_404(Album, pk=pk)
    if request.method == 'POST':

        song = Song()

        song.song_title = request.POST['song_title']
        song.audio_file = request.FILES['f-msc']
        song.album = album

        song.save()

    return redirect('music:details', album.id)




# class SongCreateView(View):
#     form_class = SongCreateForm
#
#     def post(self, request):
#         form = self.form_class(request.POST)
#
#         if form.is_valid():
#
#             song = form.save(commit=False)
#
#             song_title =

music/templates/music/CommonNav.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<!-- font awesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- own style -->
	<style type="text/css">
        {% block internal-css %}{% endblock %}
	</style>
    <script type="text/javascript">
        {% block script %}{% endblock %}
    </script>
	</head>
<body {% block load %}{% endblock %}>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
    	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" style="font-family: lucida handwriting;" href="{% url 'music:index' %}">Listen</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li {% block active-album %}{% endblock %}><a href="{% url 'music:index' %}"><i class="fa fa-dot-circle-o"></i>&nbsp&nbspAlbum</a></li>
        <li {% block active-song %}{% endblock %}><a href="{% url 'music:songs' %}"><i class="fa fa-music"></i>&nbsp&nbspSongs</a></li>
      </ul>
      <form class="navbar-form navbar-left" action="{% block search_action %}{% endblock %}" method="post">
          {% csrf_token %}
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li {% block active-add_album %}{% endblock %}><a href="{% url 'music:add-album' %}"><i class="fa fa-plus"></i>&nbsp&nbspAdd Album</a></li>
        <li class="disabled"><a><i class="fa fa-power-off"></i>&nbsp&nbspLogout</a></li>
      </ul>
    </div>
  </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

music/templates/music/Details.html
{% extends 'music/CommonNav.html' %}

{% block title %}Album Details{% endblock %}

{% block internal-css %}
	.row .well img{
      height: 320px;
      width: 100%;
      border-radius: 3px;
    }
    #my_btn1, #my_btn2{
      text-decoration: none;
      outline:none;
    }
    #t_op2{
      display: none;
    }
    #t_op2 label{
      margin-top: -3px;
    }
    #t_op2 input[type=file]{
      margin-top:5px;
    }
    /* align center model */
    .modal {
  		text-align: center;
  		padding: 0!important;
	}
	.modal:before {
  		content: '';
  		display: inline-block;
  		height: 100%;
  		vertical-align: middle;
  		margin-right: -4px;
	}
	.modal-dialog {
  		display: inline-block;
  		text-align: left;
  		vertical-align: middle;
	}
	/* model ends */
    @media(max-width: 767px){
        #t_op2 label, #t_op2 input[type=file]{
          margin-top: 0px;
        }
      #rgt-wl{
        margin-top: 40px;
      }
    }
{% endblock %}

{% block active-album %}{% endblock %}

{% block active-song %}{% endblock %}

{% block search_action %}{% url 'music:songs' %}{% endblock %}

{% block script %}
    function showAdd(){
        document.getElementById("t_op1").style.display = "none";
        document.getElementById("my_btn1").className = "btn btn-link";
        document.getElementById("t_op2").style.display = "block";
        document.getElementById("my_btn2").className = "btn btn-primary";
      }
      function showSongs(){
        document.getElementById("t_op2").style.display = "none";
        document.getElementById("my_btn1").className = "btn btn-primary";
        document.getElementById("t_op1").style.display = "block";
        document.getElementById("my_btn2").className = "btn btn-link";
      }
{% endblock %}

{% block body %}
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <div class="well well-sm">
            <img src="{{ album.album_logo.url }}">
            <h3>{{ album.album_title }} &nbsp<small>{{ album.genre }}</small></h3>
            <h4>{{ album.artist }}</h4>
          </div>
        </div>
        <div class="col-sm-8" id="rgt-wl">
            <button type="button" class="btn btn-primary" id="my_btn1" onclick="showSongs()">View All</button>
            <button type="button" class="btn btn-link" id="my_btn2" onclick="showAdd()">Add New Song</button>
            <div class="well well-sm" style="margin-top: 20px;" id="t_op1">
                <h3>All Songs</h3>
                <div class="table-responsive">
                  <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>Title</th>
                          <th>Audio File</th>
                          <th>Favorite</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for song in album.song_set.all %}
                        <tr>
                          <td>{{ song.song_title }}.{{ song.file_type }}</td>
                          <td><a href="#" class="btn btn-primary btn-sm" role="button" data-toggle="modal" data-target="#myModal_{{ forloop.counter }}">&nbsp<i class="fa fa-play"></i>&nbsp</a></td>
                           <td><a href="{% url 'music:song_favorite' album.id song.id %}" class="btn btn-default btn-sm" {% if song.is_favorite %} style="color:red;" {% endif %} role="button">&nbsp<i class="fa fa-star"></i>&nbsp</a></td>
                           <td><a href="{% url 'music:song-delete' album.id song.id %}" class="btn btn-default btn-sm" role="button">&nbsp<i class="fa fa-trash"></i>&nbsp</a></td>
                            <div class="modal fade" id="myModal_{{ forloop.counter }}" role="dialog">
                                <div class="modal-dialog">
                                    <!-- Modal content-->
                                  <div class="modal-content">
                                    <div class="modal-body">
                                        <center>
                                      <audio controls style="outline: none;">
                                        <source src="{{ song.audio_file.url }}" type="audio/mpeg">
                                      </audio>
                                      </center>
                                    </div>
                                  </div>
                                </div>
                            </div>
                        </tr>
                      {% endfor %}
                      </tbody>
                    </table>
                </div>
          </div>
          <div class="well well-sm" style="margin-top: 20px;" id="t_op2">
            <h3>Add a New Song</h3>
            <form class="form-horizontal" action="{% url 'music:add-song' album.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
              <div class="form-group">
                <label class="control-label col-sm-2" for="id_song_title">Song title:</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="id_song_title" maxlength="250" placeholder="Enter song title" name="song_title">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2" for="ad-file">Audio File:</label>
                <div class="col-sm-10">
                  <input type="File" id="ad-file" name="f-msc" style="outline: none;">
                </div>
              </div>
              <br>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-default">Submit</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>

    </div>
{% endblock %}

music/templates/music/Index.html
{% extends 'music/CommonNav.html' %}

{% block title %}Albums{% endblock %}

{% block internal-css %}
	.well img{
		height: 320px;
		width: 100%;
		border-radius: 3px;
	}
		.modal-dialog {
		  height: 80% !important;
		  padding-top:10%;
		}

		.modal-content {
		  height: 100% !important;
		  overflow:visible;
		}

		.modal-body {
		  height: 80%;
		  overflow: auto;
		}
{% endblock %}

{% block active-album %}class = "active"{% endblock %}

{% block search_action %}{% endblock %}

{% block body %}
	<div class="container">
		<div class="page-header">
			<h2>Albums</h2>
		</div>
		<div class="row">
			{% for album in albums %}
			  <div class="col-sm-4">
				<div class="well well-sm">
					<img src="{{ album.album_logo.url }}">
					<h3>{{ album.album_title }}</h3>
					<h4>{{ album.artist }}</h4>
					<a href="{% url 'music:details' album.id %}" class="btn btn-primary" role="button">View Details</a>
					<a href="{% url 'music:album-delete' album.id %}" class="btn btn-default" role="button"><i class="fa fa-trash"></i></a>
					<a href="{% url 'music:album_favorite' album.id %}" class="btn btn-default" {% if album.is_favorite %} style="color:red;" {% endif %} role="button"><i class="fa fa-star"></i></a>
				</div>
			  </div>
			{% endfor %}
			{% if album %}
				<div class="col-sm-4">
					<div class="well well-sm">
						<img src="{{ album.album_logo.url }}">
						<h3>{{ album.album_title }}</h3>
						<h4>{{ album.artist }}</h4>
						<a href="{% url 'music:details' album.id %}" class="btn btn-primary" role="button">View Details</a>
						<a href="{% url 'music:album-delete' album.id %}" class="btn btn-default" role="button"><i class="fa fa-trash"></i></a>
						<a href="{% url 'music:album_favorite' album.id %}" class="btn btn-default" {% if album.is_favorite %} style="color:red;" {% endif %} role="button"><i class="fa fa-star"></i></a>
					</div>
				</div>
			{% endif %}
		</div>
		<h4 class="text-muted text-center">{{ msg1 }}</h4>
        <p class="text-muted text-center">{{ msg2 }}</p>
		<br>
		<button type="button" class="btn btn-link btn-lg pull-right" data-toggle="modal" data-target="#coronaModal" style="text-decoration: none; outline:none; margin-left: 20px;">Corona Updates</button>
		<!-- Modal -->
		<div id="coronaModal" class="modal fade" role="dialog">
		  <div class="modal-dialog">

			<!-- Modal content-->
			<div class="modal-content">
			  <div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h3 class="modal-title">Corona Cases</h3>
			  </div>
				<div class="modal-body">
						<h4>covid-19 INDIA:</h4>
						<p>Total Confirmed &nbsp<span class="badge">{{ india_confirmed }}</span></p>
						<p>Cured / Discharged &nbsp<span class="badge" style="background-color: #5cb85c;">{{ india_recover }}</span></p>
						<p>Active Cases &nbsp<span class="badge" style="background-color: #f0ad4e;">{{ india_active }}</span></p>
						<p>Deaths &nbsp<span class="badge" style="background-color: #d9534f;">{{ india_deaths }}</span></p>
						<div class="progress">
						  <div class="progress-bar progress-bar-success" role="progressbar" style="width:{{ india_per_recover }}%">
							{{ india_recover }}
						  </div>
						  <div class="progress-bar progress-bar-warning" role="progressbar" style="width:{{ india_per_active }}%">
							{{ india_active }}
						  </div>
						  <div class="progress-bar progress-bar-danger" role="progressbar" style="width:{{ india_per_deaths }}%">
							{{ india_deaths }}
						  </div>
						</div>
						<hr>
						<h4>covid-19 MUMBAI:</h4>
						<p>Total Confirmed &nbsp<span class="badge" style="background-color: #5cb85c;">{{ mumbai_confirmed }}</span></p>
						<p>Mumbai contribution in India </p>
						<div class="progress">
						  <div class="progress-bar progress-bar-success" role="progressbar" style="width:{{ mum_per_india }}%">
							{{ mumbai_confirmed }}
						  </div>
						</div>
						<hr>
						<h4>covid-19 MAHARASHTRA:</h4>
						<p>Total Confirmed &nbsp<span class="badge">{{ maha_confirmed }}</span></p>
						<p>Cured / Discharged &nbsp<span class="badge" style="background-color: #5cb85c;">{{ maha_recovered }}</span></p>
						<p>Maharashtra recovered patients from confirmed cases </p>
						<div class="progress">
						  <div class="progress-bar progress-bar-success" role="progressbar" style="width:{{ maha_per_recover }}%">
							{{ maha_recovered }}
						  </div>
						</div>
					  </div>
			</div>

		  </div>
		</div>

	</div>
{% endblock %}

music/templates/music/Songs.html
{% extends 'music/CommonNav.html' %}

{% block title %}Songs{% endblock %}

{% block internal-css %}
	    /* align center model */
    .modal {
  		text-align: center;
  		padding: 0!important;
	}
	.modal:before {
  		content: '';
  		display: inline-block;
  		height: 100%;
  		vertical-align: middle;
  		margin-right: -4px;
	}
	.modal-dialog {
  		display: inline-block;
  		text-align: left;
  		vertical-align: middle;
	}
	/* model ends */
	.ad-sng{
		margin-right: 15px;
		padding-top:0px;
	}
{% endblock %}

{% block active-album %}{% endblock %}

{% block active-song %}class = "active"{% endblock %}



{% block script %}
{% endblock %}

{% block body %}
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
            <div class="well well-sm" style="margin-top: 20px;">
                <h3>All Songs</h3>
                <div class="table-responsive">
                  <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>Title</th>
                          <th>Audio File</th>
                          <th>Favorite</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for song in all_songs %}
                        <tr>
                          <td>{{ song.song_title }}.{{ song.file_type }}</td>
                          <td><a href="#" class="btn btn-primary btn-sm" role="button" data-toggle="modal" data-target="#myModal_{{ forloop.counter }}">&nbsp<i class="fa fa-play"></i>&nbsp</a></td>
                           <td><a href="{% url 'music:song_page_fav' song.id %}" class="btn btn-default btn-sm" {% if song.is_favorite %} style="color:red;" {% endif %} role="button">&nbsp<i class="fa fa-star"></i>&nbsp</a></td>
                           <td><a href="{% url 'music:song_page_del' song.id %}" class="btn btn-default btn-sm" role="button">&nbsp<i class="fa fa-trash"></i>&nbsp</a></td>
                            <div class="modal fade" id="myModal_{{ forloop.counter }}" role="dialog">
                                <div class="modal-dialog">
                                    <!-- Modal content-->
                                  <div class="modal-content">
                                    <div class="modal-body">
                                        <center>
                                      <audio controls style="outline: none;">
                                        <source src="{{ song.audio_file.url }}" type="audio/mpeg">
                                      </audio>
                                    </div>
                                  </div>
                                </div>
                            </div>
                        </tr>
                      {% endfor %}
                      {% if song %}
                      <tr>
                          <td>{{ song.song_title }}.{{ song.file_type }}</td>
                          <td><a href="#" class="btn btn-primary btn-sm" role="button" data-toggle="modal" data-target="#myModalspecific">&nbsp<i class="fa fa-play"></i>&nbsp</a></td>
                           <td><a href="{% url 'music:song_page_fav' song.id %}" class="btn btn-default btn-sm" {% if song.is_favorite %} style="color:red;" {% endif %} role="button">&nbsp<i class="fa fa-star"></i>&nbsp</a></td>
                           <td><a href="{% url 'music:song_page_del' song.id %}" class="btn btn-default btn-sm" role="button">&nbsp<i class="fa fa-trash"></i>&nbsp</a></td>
                            <div class="modal fade" id="myModalspecific" role="dialog">
                                <div class="modal-dialog">
                                    <!-- Modal content-->
                                  <div class="modal-content">
                                    <div class="modal-body">
                                        <center>
                                      <audio controls style="outline: none;">
                                        <source src="{{ song.audio_file.url }}" type="audio/mpeg">
                                      </audio>
                                    </div>
                                  </div>
                                </div>
                            </div>
                        </tr>
                      {% endif %}
                      </tbody>
                    </table>
                </div>
          </div>
        </div>
          <a href="{% url 'music:song-create' %}" class="btn btn-link pull-right ad-sng" role="button" style="text-decoration: none;"><i class="fa fa-plus"></i>&nbsp&nbspAdd Song</a>
      </div>
        <h4 class="text-muted text-center">{{ msg1 }}</h4>
        <p class="text-muted text-center">{{ msg2 }}</p>
    </div>
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}
        <div class="col-sm-10">
          {{ field }}<span class="text-danger small">{{ field.errors }}</span>
        </div>
    </div>
{% endfor %}

music/templates/music/index_search.html
{% extends 'music/CommonNav.html' %}

{% block title %}Albums{% endblock %}

{% block internal-css %}
	.well img{
		height: 320px;
		width: 100%;
		border-radius: 3px;
	}
{% endblock %}

{% block active-album %}class = "active"{% endblock %}

{% block search_action %}{% endblock %}

{% block body %}
	<div class="container">
		<div class="page-header">
			<h2>Albums</h2>
		</div>
		<div class="row">
          <div class="col-sm-4">
            <div class="well well-sm">
                <img src="{{ album.album_logo.url }}">
                <h3>{{ album.album_title }}</h3>
                <h4>{{ album.artist }}</h4>
                <a href="{% url 'music:details' album.id %}" class="btn btn-primary" role="button">View Details</a>
                <a href="{% url 'music:album-delete' album.id %}" class="btn btn-default" role="button"><i class="fa fa-trash"></i></a>
                <a href="{% url 'music:album_favorite' album.id %}" class="btn btn-default" {% if album.is_favorite %} style="color:red;" {% endif %} role="button"><i class="fa fa-star"></i></a>
            </div>
          </div>
		</div>
		<h3>{{ error_message }}</h3>
	</div>
{% endblock %}